// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn1aFlWuIUMwFFuFippaaDCp3RtCy6k10',
    appId: '1:973090020280:web:bb03d3d9b151c8f2970d4d',
    messagingSenderId: '973090020280',
    projectId: 'app-android-invemtarios',
    authDomain: 'app-android-invemtarios.firebaseapp.com',
    storageBucket: 'app-android-invemtarios.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYdyyt_niohs0vxiTY_u2HQBA1UioqF0',
    appId: '1:973090020280:android:f798ec5fa94fdc30970d4d',
    messagingSenderId: '973090020280',
    projectId: 'app-android-invemtarios',
    storageBucket: 'app-android-invemtarios.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKUPzBNUYbwHjQudaWFVWuuYPk-MZgeDc',
    appId: '1:973090020280:ios:e06728a56a9d5ba6970d4d',
    messagingSenderId: '973090020280',
    projectId: 'app-android-invemtarios',
    storageBucket: 'app-android-invemtarios.firebasestorage.app',
    iosBundleId: 'com.example.gestionInventarioPrestamosPatrick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKUPzBNUYbwHjQudaWFVWuuYPk-MZgeDc',
    appId: '1:973090020280:ios:e06728a56a9d5ba6970d4d',
    messagingSenderId: '973090020280',
    projectId: 'app-android-invemtarios',
    storageBucket: 'app-android-invemtarios.firebasestorage.app',
    iosBundleId: 'com.example.gestionInventarioPrestamosPatrick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn1aFlWuIUMwFFuFippaaDCp3RtCy6k10',
    appId: '1:973090020280:web:5cd350598f53e417970d4d',
    messagingSenderId: '973090020280',
    projectId: 'app-android-invemtarios',
    authDomain: 'app-android-invemtarios.firebaseapp.com',
    storageBucket: 'app-android-invemtarios.firebasestorage.app',
  );
}
